### ISSUE TITLE
Is NAMD supported by Ensemble Toolkit?

### ISSUE THREAD

**Issue by dww100** [radical-collaboration/GB-SC18#1]
At least initially, we will be running simulations using NAMD. This ticket is just to flag that in case there are any issues with this either from our end or needed support from target sites (as discussed in today's telco).

**Comment by vivek-bala** [comment]
Hi Dave, as long as the kernel (in this case NAMD) is up and running on the cluster that you want to use, Ensemble toolkit (EnTK) will be able to use this kernel. By design, EnTK is not bound to any specific kernels.

**Comment by shantenujha** [comment]
Vivek - I agree. But I asked Dave to open a ticket to ensure that we test with NAMD as well, as we don't have regular usage.  Is this tested locally?

**Comment by vivek-bala** [comment]
We had a namd example in a previous version targetting stampede. I'll dig that out.

**Comment by vivek-bala** [comment]
Example of the namd kernel: https://github.com/radical-cybertools/radical.ensemblemd/blob/master/src/radical/ensemblemd/kernel_plugins/md/namd.py. This might require changes in terms of the executable or arguments that we want to use.

I believe the namd version on stampede is now 2.10 and 2.11 though.

**Comment by dww100** [comment]
Great - thanks
