### ISSUE TITLE
Linking directories

### ISSUE THREAD

**Issue by sjzasada** [radical-collaboration/GB-SC18#10]
Hi, 

Is it possible to use k1.link_input_data to link an entire directory structure between stages, or is it only possible to link individual files? 

Thanks, 

Stefan

**Comment by vivek-bala** [comment]
Hey Stefan, currently all transfer operations (copy, link, upload, download) are only file based. If there are a large number of files in that folder, I would suggest creating a tarball of that folder in order to transfer. Another idea might be to read and write from pre-defined locations on the remote machine. It depends on the application, some of the factors you might want to consider are the number of files that need to be transferred and their size.

**Comment by sjzasada** [comment]
And is the $SHARED variable only expanded for file transfer operations, or can it also be used in kernel arguments, e.g. k.arguments = [“—inputfile=$SHARED/foo“]?

Thanks,

Stefan



On 26 Jun 2017, at 23:31, Vivekanandan (Vivek) Balasubramanian <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey Stefan, currently all transfer operations (copy, link, upload, download) are only file based. If there are a large number of files in that folder, I would suggest creating a tarball of that folder in order to transfer. Another idea might be to read and write from pre-defined locations on the remote machine. It depends on the application, some of the factors you might want to consider are the number of files that need to be transferred and their size.

**Comment by sjzasada** [comment]
Thanks. Is it possible to create a per instance shared directory (ie one that can be shared between all the steps in an instance)?

Stefan



On 26 Jun 2017, at 23:31, Vivekanandan (Vivek) Balasubramanian <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey Stefan, currently all transfer operations (copy, link, upload, download) are only file based. If there are a large number of files in that folder, I would suggest creating a tarball of that folder in order to transfer. Another idea might be to read and write from pre-defined locations on the remote machine. It depends on the application, some of the factors you might want to consider are the number of files that need to be transferred and their size.

**Comment by vivek-bala** [comment]
> And is the $SHARED variable only expanded for file transfer operations, or can it also be used in kernel arguments, e.g. k.arguments = [“—inputfile=$SHARED/foo“]?

Yes, it is expanded only for file transfer operations.

> Thanks. Is it possible to create a per instance shared directory (ie one that can be shared between all the steps in an instance)?

Yes, any file staged into the $SHARED location can be accessed by every other task.
