### ISSUE TITLE
EoP vs PoE

### ISSUE THREAD

**Issue by sjzasada** [radical-collaboration/GB-SC18#11]
Can you help me understand the difference between EoP and PoE? The diagrams shown in the examples section of the documentation look effectively the same. I assume that an EoP executes all stages independently of the other instances whereas PoE waits for all instances at a particular stage to finish before starting the next stage. 

Sorry if I've missed the explanation in the docs somewhere.

**Comment by vivek-bala** [comment]
Hi Stefan, sure. Your understanding is correct. An 'Ensemble' consists of entities that have no dependencies and can be executed concurrently. A 'Pipeline' consists of entities that have a linear temporal dependency (a stage number is used to describe the temporal ordering). 

An EoP consists of Pipelines that can be concurrently executed. Note the dependency within each of the Pipeline is to be maintained. This pattern allows the Pipelines to be executed at different rates (so Pipeline 1 can be in stage 2 with Pipeline 2 in stage 3 and Pipeline N in stage 1). A PoE consists of 1 Pipeline with multiple Ensembles (organized into different 'stages') that have a temporal dependence (so stage 2 can start executing only after all the ensemble members/tasks of stage 1 have finished executing).

Please let me know if that helps understanding. Happy to discuss this in further detail over the ticket or over a call.

**Comment by sjzasada** [comment]
Thanks. Is there a way to run selected steps from an EoP, e.g. if I just wanted to run steps 1-6, then step 9?

On 26 Jun 2017, at 23:26, Vivekanandan (Vivek) Balasubramanian <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Stefan, sure. Your understanding is correct. An 'Ensemble' consists of entities that have no dependencies and can be executed concurrently. A 'Pipeline' consists of entities that have a linear temporal dependency (a stage number is used to describe the temporal ordering).

An EoP consists of Pipelines that can be concurrently executed. Note the dependency within each of the Pipeline is to be maintained. This pattern allows the Pipelines to be executed at different rates (so Pipeline 1 can be in stage 2 with Pipeline 2 in stage 3 and Pipeline N in stage 1). A PoE consists of 1 Pipeline with multiple Ensembles (organized into different 'stages') that have a temporal dependence (so stage 2 can start executing only after all the ensemble members/tasks of stage 1 have finished executing).

Please let me know if that helps understanding. Happy to discuss this in further detail over the ticket or over a call.

**Comment by vivek-bala** [comment]
Apologies for the delay. This is not possible in the master branch but exists in devel. I will create an example for this as well. Something more for the documentation as well. Thanks.
