### ISSUE TITLE
Authentication issues on Archer running bac_ensembletk_runner.py

### ISSUE THREAD

**Issue by dww100** [radical-collaboration/GB-SC18#12]
I can login to Archer using an ssh-key using the command:
`ssh d137dww@login.archer.ac.uk`
But when I try to run the bac_ensembletk_runner.py based on ensemble toolkit I get an error including "prompted for unknown password" does anyone know what is going on?

My config.json file looks like:
```
{
    "epsrc.archer": {
        "project": "d137-dave",
        "queue": "standard",
        "schema": "ssh",
        "user": "d137dww"
    }
}
```

I have zipped up the config and log files in [bac_test.zip](https://github.com/radical-collaboration/GB-SC18/files/1145301/bac_test.zip)

**Comment by vivek-bala** [comment]
Hi Dave, can you confirm that you can login to Archer without a password? Any chance you have multiple usernames/accounts on Archer?

**Comment by dww100** [comment]
@vivek-bala I can definitely login without a password from using standard ssh, do you mean via some Radical component?

I do have multiple Archer accounts - I was working on the basis that this would be handled by the use of the correct username - do you agree that the json and command line above agree on that? Or am i misunderstanding something?

**Comment by andre-merzky** [comment]
your ~/.ssh/config might configure ssh access for a different user name?  We had a case like that in the past.  If that is not the case, would you mind running with:

```
RADICAL_SAGA_PTY_VERBOSE=DEBUG
RADICAL_SAGA_PTY_LOG_TGT=rs.log
```

and attach the resulting log file, please?  Thanks!

**Comment by dww100** [comment]
@andre-merzky  My ~/.ssh/config contains entries for three (two current) logins for Archer. The entries look like the following for each account (d137 is the account I am trying to use):
```
Host                    archerd137
HostName           login.archer.ac.uk
User                    d137dww
```
Do I have to remove all other archer entries?

**Comment by andre-merzky** [comment]
So you do something like `ssh archerd137`?  That should not interfere with our layers, no need to remove those entries.

Vivek, is the username passed through to the RP session?   David, please do send that logfile from above, if possible.

Thanks, Andre.

**Comment by vivek-bala** [comment]
Hi Dave, can you edit to the following and try again:

```
Host                    archerd137 login.archer.ac.uk epsrc.archer
HostName           login.archer.ac.uk
User                    d137dww
```

**Comment by vivek-bala** [comment]
@andre-merzky The username provided by the user is passed on to the RP context. Is that what you were asking? Also, RADICAL_SAGA_PTY_VERBOSE is accepted in RP/master as well, right?

@dww100 The config looks ok. But I can't see the actual command that gets executed to login to archer in the log that you attached. Can you also set RADICAL_SAGA_PTY_VERBOSE=DEBUG please?

**Comment by dww100** [comment]
@vivek-bala Editing my .ssh/config as suggested appear to have done the trick - thanks to you and @andre-merzky

**Comment by vivek-bala** [comment]
Great! Glad to hear that.
