### ISSUE TITLE
NAMD execution cores on Archer

### ISSUE THREAD

**Issue by sjzasada** [radical-collaboration/GB-SC18#13]
Hi, 

We are using the following snippet to run NAMD on Archer:

		k2 = Kernel(name="md.namd")
		k2.arguments = ["%s/mineq_confs/eq0.conf" % rootdir]
		k2.cores = 8

Based on various examples. However, NAMD reports: 

		Info: Running on 1 processors, 1 nodes, 1 physical nodes.

i.e. it's only running on a single core. Examining the radical_pilot_cu_launch_script.sh reveals: 

		/opt/cray/alps/5.2.4-2.0502.9822.32.1.ari/bin/aprun -n 1 /usr/local/packages/namd/namd-2.9/bin/namd2 "tyk2-l01/mineq_confs/eq0.conf"

- it looks like the number of cores is not getting passed through to aprun from the kernel, which is what we expected would happen. Why is this?

**Comment by vivek-bala** [comment]
Indeed! I think you are using the EoP pattern, where the cores are not getting translated and default to 1. Hotfix coming up.

**Comment by vivek-bala** [comment]
Hey Stefan, please test the master branch of radical.ensemblemd again. I tested to make sure the core specification is forwarded downstream. 

There seem to have been some procedural changes in uploading packages to pypi. I will check them and upload to pypi later.

**Comment by sjzasada** [comment]
Thanks, it looks like the core number is propagating now.
