### ISSUE TITLE
TIES protocol questions

### ISSUE THREAD

**Issue by kristofarkas** [radical-collaboration/GB-SC18#19]
### Questions

- `rootdir` has to be copied over, but only once. If `rootdir` is tarred up, then you have to untar it at then other end. Where would you put that 1 untaring proccess? Having an untar `Stage` would run for all pipelines.
- The executable (namd2) has to be executed in `rootdir`. Is this how Radical works?
- Setting up a `Task` correctly. How to specify an output pipe for the namd2 executable, i.e. `namd2 min.conf >& min.log` is equivalent to:
```
t  = Task()
t.executable = ['/u/sciteam/jphillip/NAMD_build.latest/NAMD_2.12_CRAY-XE-MPI-BlueWaters/namd2']
t.arguments = ['min.conf', '>&', 'min.log']
```
?

**Comment by kristofarkas** [comment]
Is subclassing `Task` like this okay?

```
class NamdTask(Task):
    def __init__(self):
        super(NamdTask, self).__init__()
        self.executable = ['/u/sciteam/jphillip/NAMD_build.latest/NAMD_2.12_CRAY-XE-MPI-BlueWaters/namd2']
```

**Comment by jdakka** [comment]
@kristofarkas the subclassing Task should work. In regard to the `rootdir` @vivek-bala will explain the data movement in RADICAL Pilot

**Comment by vivek-bala** [comment]
Hey Kristof, I initially thought it was an issue of data movement, but it isn't. When we have a **set** of Pipelines to execute, they (by definition) can execute in any order. With that in mind, keeping a Stage in any of the Pipelines so that it executes only once cannot be guaranteed. I see three solutions:

1) Move the untarred folder on to the remote resource manually before execution of the workflow 
2) Submit two workflow objects where the first workflow object consists of 1 Pipeline with 1 Stage consisting of 1 Task. This Task would simply stage the tarred file and untar it on the remote resource.
3) Keep one workflow object consisting of a set of Pipelines (as it exists right now). Keep Stage 1 as the untarring stage but modify the executable such that it tests the following:
if the untarred folder exists:
    do nothing
else:
    untar


I would say option 1 is the quickest. Note that in option 3, the Tasks still do execute but all they only one of the Tasks untars.

Let me know if that makes sense.

**Comment by kristofarkas** [comment]
Option 1 would prevent the user from doing everything on the local machine.
Option 2 sound like the most elegant solution. Would you make two `AppManager`s with the same `ResouceManager`? and run them consecutively? How could you check if the first App ran?
Option 3 could have problems if two (or more) Taks' start untarring before an utarred folder exists. 

`ResourceManager` has a property called `shared_data`. How does that work? Can I set this to be a whole directory? Or if it only accepts files, I could set all the files in my input directory to this list, but would that preserve the directory structure inside the input directory on the remote machine?

Can I have a `Task` execute `namd2` using an input from this copied over directory/file? If we do Option 2, then this input file would just be a 'normal' folder on the remote, right?

**Comment by vivek-bala** [comment]
I would recommend automating option 1. You can spawn a separate process which does an scp/gsiscp of the data to the required location on the remote machine.

Option 2 is also ok, but might require some additional coding than the above suggestion. If you want to go ahead with this option, please use the fix/resubmission branch (https://github.com/vivek-bala/radical.entk/tree/fix/resubmission). There is no example describing the usage yet, so I am adding the following snippet:

```
# Set argument autoterminate to False in the AppManager, 
# this lets you submit multiple pipelines but remember then 
# you have to actively cancel the resource allocation (see below)
appman = AppManager(port = 32773, autoterminate=False)

try:
    # Assign first pipeline to AppMngr and run
    appman.assign_workflow(p1)
    # Following is a blocking call
    appman.run() 

    # Assign second pipeline to AppMngr and run
    appman.assign_workflow(p2)
    appman.run() 

exception Exception as ex:
    print 'Error: ', ex
    print traceback.format_exc()
    
finally:
    # Once all pipelines are done, cancel the resource allocation
    appman.resource_terminate()
```

**Comment by vivek-bala** [comment]
> ResourceManager has a property called shared_data. How does that work? Can I set this to be a whole directory? Or if it only accepts files, I could set all the files in my input directory to this list, but would that preserve the directory structure inside the input directory on the remote machine? Can I have a Task execute namd2 using an input from this copied over directory/file? If we do Option 2, then this input file would just be a 'normal' folder on the remote, right?

Unfortunately, there is no folder staging yet, only files can be staged. You can do something similar to what Stefan and Jumana did in the esmacs scripts. See the following (this preserves the folder structure):
* https://github.com/radical-collaboration/GB-SC18/blob/master/scripts/esmacs/bac_runner_entk_0-6_barrier.py#L243-L249
* https://github.com/radical-collaboration/GB-SC18/blob/master/scripts/esmacs/bac_runner_entk_0-6_barrier.py#L59-L60

Let me know if that helps.

**Comment by jdakka** [comment]
@kristofarkas do you have everything you need to resolve this issue?

**Comment by kristofarkas** [comment]
@jdakka yes
