### ISSUE TITLE
TIES Cores Requirements

### ISSUE THREAD

**Issue by jdakka** [radical-collaboration/GB-SC18#21]
@kristofarkas @sjzasada 

In the radical.py script you specify the # of cores per pipeline = 8 however in the workflow.sh file you're requesting 32 threads for each pipeline (i.e. 16 cores). With which requirement should I proceed?

**Comment by kristofarkas** [comment]
The `workflow.sh` file is what I used to submit this job via qsub on BW. There I had 32 cores but it will run with less too. I set it to 8 because the ESMACS script had 8 threads. I think we use even more than 32 per pipeline (@dww100 ?) in production runs.

**Comment by jdakka** [comment]
@kristofarkas If you look back at workflow.sh there you request 1 process using 32 cores spawn +ppn 30 threads, can you explain why 30 threads (i.e. is this a NAMD constraint?)?

**Comment by kristofarkas** [comment]
I just copied jphillip's (lead NAMD developer, hosting namd2 in his directory on BW) run script. Some of the cores are reserved for managing tasks. But probably you can just run a normal namd2 as you did with the esmacs runs.

**Comment by jdakka** [comment]
One last thing: the NAMD developer jphillip has changed the NAMD MPI path. This will change in the protocols. These are the versions currently available: 

```dakka@h2ologin1:/u/sciteam/jphillip/NAMD_build.latest> ls
CRAY-XE-ugni-BlueWaters-memopt           CRAY-XE-ugni-smp-BlueWaters-memopt        NAMD_2.12_CRAY-XE-ugni-smp-BlueWaters-CUDA-memopt
CRAY-XE-ugni-smp-BlueWaters-CUDA-memopt  NAMD_2.12_CRAY-XE-ugni-BlueWaters-memopt  NAMD_2.12_CRAY-XE-ugni-smp-BlueWaters-memopt
```
I'm testing the performance of `NAMD_2.12_CRAY-XE-ugni-smp-BlueWaters-memopt`
