### ISSUE TITLE
TIES Execution 

### ISSUE THREAD

**Issue by jdakka** [radical-collaboration/GB-SC18#22]
@kristofarkas @sjzasada @dww100 

For each of the 4 stages of ties ('min', 'eq1', 'eq2', 'prod') can you provide a rough estimate for duration of execution given the currently provided /bace1_b01 testing system?

**Comment by kristofarkas** [comment]
I deliberately reduced the number of steps in each step for the whole simulation to run quickly. Runtime will depend on number of cores per pipeline also. 
Is this a good idea? I assume there is no difference between running a 50000 vs a 5000 step simulation wrt testing Radical?

**Comment by jdakka** [comment]
@kristofarkas for testing a shorter simulation time the 300 time step system you provided is perfectly fine in order to get benchmark data. For the use-case requirements however it would be good to get an estimate on a typical production run so we know what kind of wall time we're dealing with.

**Comment by jdakka** [comment]
Closing issue with reference from use-case doc:

ESMACS/TIES No of sim steps per task: 
eq0 - 1,000 (minimization)
eq1 - 30,000
eq2 - 970,000
sim1 - 2,000,000
