### ISSUE TITLE
Pipeline stalls after (during) first Stage 

### ISSUE THREAD

**Issue by kristofarkas** [radical-collaboration/GB-SC18#26]
I am trying to run a multi stage pipeline on *localhost*. The first stage seem to execute correctly, but then the next ones don't.

If I run with verbosity INFO, after some time the script outputs this every 10 seconds:
```
2017-11-25 19:59:35,499: radical.entk.task_manager: MainProcess                     : heartbeat      : INFO    : Received heartbeat response
2017-11-25 19:59:35,501: radical.entk.task_manager: MainProcess                     : heartbeat      : INFO    : Sent heartbeat request
2017-11-25 19:59:35,502: radical.entk.task_manager: task-manager                    : MainThread     : INFO    : Received heartbeat request
2017-11-25 19:59:35,503: radical.entk.task_manager: task-manager                    : MainThread     : INFO    : Sent heartbeat response
```
and never returns. 

After this I tried a 1 Stage setup, and that results in this same behaviour.

Using the `experiment/jdakka` branch.

**Comment by jdakka** [comment]
Could you check to make sure you have the following stack:
(Apologies we are still merging all our branches) 

[saga-python](https://github.com/radical-cybertools/saga-python.git) 
branch: rc/v0.46.3

[radical-utils](https://github.com/radical-cybertools/radical.utils.git)
branch: rc/v0.46.3

[radical-pilot](https://github.com/radical-cybertools/radical.pilot.git)
branch: rc/v0.46.3

[radical-entk](https://github.com/vivek-bala/radical.entk.git)
branch: experiment/jdakka

Before running set the following variables: 

export RADICAL_PILOT_DBURL= URL
export SAGA_PTY_SSH_TIMEOUT=2000
export RADICAL_PILOT_PROFILE=True
export RADICAL_ENMD_PROFILE=True
export RADICAL_ENMD_PROFILING=1
export RP_ENABLE_OLD_DEFINES=True
export PATH=/usr/sbin:$PATH
myproxy-logon -l <user -s tfca.ncsa.illinois.edu

I'll also create a separate ticket for you and  @mturilli to setup an account for you on one of our designated VMs where we currently run all our jobs. 

If all that is correct could you share the script that you are trying to run? I can do a quick run on the VM.

**Comment by jdakka** [comment]
I've updated instructions for running the protocols depending on the configuration of the MD engine:
https://github.com/radical-collaboration/RADICAL-UCL/wiki/RCT

**Comment by kristofarkas** [comment]
I had the wrong branch of radical* installed. Changing to rc/v0.46.3 fixed the problem.
