### ISSUE TITLE
Remote pipeline of ensembles

### ISSUE THREAD

**Issue by sjzasada** [radical-collaboration/GB-SC18#4]
I'm trying to run the pipeline of ensembles script in section 5.1.1 of the ensemblemd documentation remotely, specifically on the archer platform. 

I've configured ~/.ssh/config to log into archer with my username on the system (stef1). ssh archer works fine. 

I've also configured config.json with my project info: 

	"epsrc.archer"  : {
				"project"  : "d137-stef",
				"queue"    : "standard",
				"schema"   : "ssh",
				"cores": 16
			}

As far as I can tell, there is a configuration file for archer already in `myenv/lib/python2.7/site-packages/radical/pilot/configs/resource_epsrc.json`

This file suggests the work path is set as follows:

`/work/`id -gn`/`id -gn`/$USER`

If I execute this on my archer login, I get `/work/d137/d137/stef1` - i.e. the correct path. 

However, when I run the following:

`RADICAL_ENTK_VERBOSE=REPORT python pipeline_of_ensembles.py epsrc.archer`

I receive an error, the root of which is:

`#PBS -o /work/e10/e10/stef/radical.pilot.sandbox/rp.session.parkin.lan.stef.017225.0001-pilot.0000/bootstrap_1.out `

which suggests that somehow the work path is being set incorrectly, i.e. using my stef username and resolving to the e10 project. Note e10 is no longer active. 

Can you let me know how this is happening, how exactly this path is set, and how it can be fixed? 

Many thanks, 

Stefan

**Comment by sjzasada** [comment]
Further to this, if I change the resource_epsrc.json file to manually set the path of my work dir:

        "default_remote_workdir"      : "/work/d137/d137/stef1/",

I get the following error: 

```
Job waiting on queue...2017-02-28 12:05:13,821: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: ERROR   : Pilot launching failed! (invalid dir '/work/d137/d137/stef1/foodir/radical.pilot.sandbox/rp.session.parkin.lan.stef.017225.0007-pilot.0000/': mkdir: cannot create directory `/work/d137/d137': Permission denied
sh: cd: /work/d137/d137/stef1/foodir/radical.pilot.sandbox/rp.session.parkin.lan.stef.017225.0007-pilot.0000/: Not a directory
```

This suggests two things I think:

1) The original setting of `/work/id -gn/id -gn/$USER` is picking up $USER from my local machine, not Archer.
2) That radical pilot is trying to create a folder that exists (/work/d137/d137) for some reason. 

Note, regardless of how long the path is after /work/d137/d137 (and whether subsequent directories exist or not), radical always tries to create a directory at this location.  Why is this? Am I missing something in the documentation?

**Comment by vivek-bala** [comment]
Hey Stefan,

Quick question: are you running the entk (client) script on your laptop and then specifying the resource as archer or is the entk script also running on archer? 

To help understand the difference, just added a document describing local vs remote execution to the repo: https://github.com/radical-collaboration/GB-SC18/blob/master/docs/execution_modes.md

**Comment by vivek-bala** [comment]
> Note, regardless of how long the path is after /work/d137/d137 (and whether subsequent directories exist or not), radical always tries to create a directory at this location. Why is this? Am I missing something in the documentation?

By default, I think the user should be able to specify where the sandbox can be created. I'm not sure if something different is configured for archer. @andre-merzky  any idea? (i'm working on reviving my archer account, incase you have an answer already)

**Comment by sjzasada** [comment]
Thanks. 

I can confirm I am running the client from my laptop. 

There is definitely something wrong with the way the archer resource_epsrc.json script works when setting the remote working directory, specifically with `/work/id -gn/id -gn/$USER`

Since this resolves to `/work/e10/e10/stef` (i.e. not my group, which is d137, or my username which is stef1). Possibly this is cached somewhere from a previous run? 

Anyway, hardcoding the work dir path removes this problem, but it doesn't remove the problem of radical pilot trying to create a directory that already exists, i.e. /work/d137/d137. 

Any help resolving this would be much appreciated. 

Stefan

**Comment by sjzasada** [comment]
Actually, I think I know what is happening here. Radical is using my username on my local system to log into archer (the username is stef on both systems). I actually want it to use the username stef1 (my active archer account). 

My reading of [this page](http://radicalensemblemd.readthedocs.io/en/latest/installation.html#preparing-the-environment) suggests that the way to specify your username on a system is to put it into the ~/.ssh/config file, where I have: 

```
Host archer
                HostName login.archer.ac.uk
                User stef1
```
 
However, it seems that only the hostname is read from here, not the username? Anyway, by manually specifying my username in the pipeline_of_ensembles.py script, I can now submit to the correct account, and it appears to run ok. 

Because the pipeline_of_ensembles.py example script configures the `ResourceHandle` from the config.json file based on the argument passed to the script, it seems a bit odd that I have to manually specify my username. I can't seem to find where the syntax of the config.json file is specified, but I imagine that it is possible to specify a username on a resource by resource basis? 

Thanks for all your help!

**Comment by andre-merzky** [comment]
Hi Stefan, 

can you please send the error message / stack trace for the failing folder creation?  I am not exactly sure where that kicks in.  Thanks!

Re path construction: `id -gn` returns the *effective* group ID.  It might well be that you are in different unix groups, but that the effective ID differs on the head node and during job  runtime, or when opening a new ssh shell.  What do you get on `ssh localhost id -gn`?

Thanks, Andre

**Comment by sjzasada** [comment]
Hi Andre, 

I think I've solved the problem (see last comment). I was expecting my username to be picked up from ~/.ssh/config but this isn't the case, so radical pilot was logging into archer with the wrong account. 

Thanks,

Stefan

**Comment by andre-merzky** [comment]
Ah, I missed that indeed - thanks for the note!
