### ISSUE TITLE
MongoDB/blocked outbound backend nodes

### ISSUE THREAD

**Issue by sjzasada** [radical-collaboration/GB-SC18#5]
Sorry for all the questions. 

I'm getting errors on Archer because the backend nodes don't have outbound internet access, and therefore cannot see the mongodb server. The error is: 

```
Traceback (most recent call last):
  File "/work/d137/d137/stef1/foodir/radical.pilot.sandbox/rp.session.parkin.local.stef.017226.0005-pilot.0000/rp_install/bin/radical-pilot-agent-multicore.py", line 666, in <module>
    bootstrap_3()
  File "/work/d137/d137/stef1/foodir/radical.pilot.sandbox/rp.session.parkin.local.stef.017226.0005-pilot.0000/rp_install/bin/radical-pilot-agent-multicore.py", line 481, in bootstrap_3
    _, mongo_db, _, _, _  = ru.mongodb_connect(cfg['mongodb_url'])
  File "/work/d137/d137/stef1/foodir/radical.pilot.sandbox/rp.session.parkin.local.stef.017226.0005-pilot.0000/rp_install/lib/python2.7/site-packages/radical/utils/misc.py", line 94, in mongodb_connect
    mongo = pymongo.MongoClient (host=host, port=port, ssl=ssl)
  File "/work/e290/shared/shared_pilot_ve_20150924/lib/python2.7/site-packages/pymongo/mongo_client.py", line 377, in __init__
    raise ConnectionFailure(str(e))
pymongo.errors.ConnectionFailure: [Errno 111] Connection refused
```

I seem to recall Shantenu telling me there was a way around this, but I can't find it in the documentation (because I'm not sure what to look for). Is it possible to deal with situations like this, and can you point me to the right place to look? 

Thanks, 

Stefan

**Comment by dww100** [comment]
When I asked Iain Bethune @ EPCC about this I got the following response:

> It is possible to set up (but somewhat fiddly), by tunnelling traffic through the login nodes using the RSIP protocol.  I wrote a white paper a few years ago, which has all the relevant info and a few examples: http://www.archer.ac.uk/documentation/white-papers/rsip/ARCHER_wp_RSIP.pdf

**Comment by vivek-bala** [comment]
Hey Stefan, David, I believe radical pilot (RP) should already be doing that on Archer. ```/work/e290/shared/shared_pilot_ve_20150924``` might need a refresh though since mlab versions have changed since that date. If so, I think @andre-merzky  might have to rebuild that.

Meanwhile could I ask you the following:

* Is the above error reproducible? (just to rule out temporary network issues)
* We recently had a round of testing (of RP) where Archer was reported to be working and made a fresh release (v0.45). Could you reinstall/upgrade RP and its dependencies on the client side and try again please. You can reinstall/upgrade using 
```pip install radical.pilot saga-python radical.utils --upgrade```

**Comment by sjzasada** [comment]
The problem happens consistently every time the application is run. 

Furthermore, submitting the following command to the queue on Archer:

`nc -zv 193.60.241.34 27017`

Returns the result: 

`nc: connect to 193.60.241.34 port 27017 (tcp) failed: Network is unreachable`

Upgrading the client side has had no effect. 

Thanks, 

Stefan

**Comment by vivek-bala** [comment]
Hi Iain,

We are running into some MongoDB connectivity issues on Archer using v0.45
of RP. Could you let us know if you encountered this issue during the
testing or if any specific configuration ( e.g. internal vs external
mongodb) was required?

I'm waiting for my Archer pwd to be reset in order to test this myself, but
in case you had any quick answers/pointers to this issue.

Thanks
Vivek

**Comment by ibethune** [comment]
Hi all,

Sorry @dww100 when you emailed me I wasn't aware you were talking in the context of running RP, hence my answer was somewhat general!

Actually, we did not test on ARCHER during the 0.45 release testing phase.  However, I just ran the 01_unit_details.py script and it ran just fine (barring https://github.com/radical-cybertools/radical.pilot/issues/1254).  I used the `epsrc.archer` config.  If it is still repeatable for you I'm not sure what to suggest.

@sjzasada what you found with `nc` is expected.  There is no direct route from the compute nodes to the outside internet.  RP sets up a series of tunnels that should sort that out.

**Comment by vivek-bala** [comment]
Thanks @ibethune. It is my understanding too, that RP sets up the tunneling mechanism. 

@sjzasada Could you rerun with some environment variables setup ```RADICAL_VERBOSE=DEBUG``` ```RADICAL_LOG_TGT=radical.log```? Once done please share your pilot folder (on archer) and radical.log (on client). 

@andre-merzky do you see any other triggers for this issue?

**Comment by sjzasada** [comment]
I've run this with the extra logging. Please find the requested files attached. 

[rp.session.parkin.lan.stef.017228.0000-pilot.0000.zip](https://github.com/radical-collaboration/GB-SC18/files/816843/rp.session.parkin.lan.stef.017228.0000-pilot.0000.zip)

[radical.txt](https://github.com/radical-collaboration/GB-SC18/files/816847/radical.txt)

Thanks, 

Stefan

**Comment by andre-merzky** [comment]
Stefan, 

I think your problem is that the tunnel gets not created:

```
$ cat bootstrap_1.err
--------------------------------------------------------------------------------
This is a private computing facility. Access to this service is limited to those
who have been granted access by the operating service provider on behalf of the
contracting authority and use is restricted to the purposes for which access was
granted. All access and usage are governed by the terms and conditions of access
agreed to by all registered users and are thus subject to the provisions of the
Computer Misuse Act, 1990 under which unauthorised use is a criminal offence.

If you are not authorised to use this service you must disconnect immediately.
--------------------------------------------------------------------------------

Permission denied (publickey,keyboard-interactive).
Python 2.7.6
kill: 8787: No such process
```

Can you please make sure that `ssh localhost` works on the archer headnode?  You may need to set up an ssh keypair for that.

Iain, IIRC, there existed some documentation on ssh key setup for archer - do you remember if that is indeed the case, and where that documentation lives?

**Comment by ibethune** [comment]
There is this: http://extasy-workflows.readthedocs.io/en/latest/pages/trouble.html#error-permission-denied-publickey-keyboard-interactive-in-agent-stderr

**Comment by andre-merzky** [comment]
thanks Iain!

**Comment by sjzasada** [comment]
Thanks guys, I'll try this and let you know what happens.

Stefan

**Comment by sjzasada** [comment]
Thanks for all the help everyone. I set up ssh localhost and now everything works for me on Archer.

**Comment by vivek-bala** [comment]
Great! Glad to hear that.
