### ISSUE TITLE
Staging directories

### ISSUE THREAD

**Issue by sjzasada** [radical-collaboration/GB-SC18#8]
Hi, 

The documentation here: http://radicalensemblemd.readthedocs.io/en/latest/api/api_buildingblocks.html#kern-api

Suggests that the `upload_input_data` parameter of `radical.ensemblemd.Kernel` can be used to uploaded both files and directories. It seems to work ok uploading files, but if I specify a directory nothing seems to happen, not even an error.  Have I missed something? 

Thanks, 

Stefan

**Comment by vivek-bala** [comment]
Hi Stefan, that is indeed an error with the documentation. Currently, only files can be staged with any of the staging directives. Apologize for that.

@andre-merzky : Hey Andre, since we are getting multiple requests for folder transfer, can we revisit https://github.com/radical-cybertools/radical.pilot/issues/936 ? I believe there was also a ticket from Jan-Hendrik.

**Comment by vivek-bala** [comment]
Moving from email to issue tracker. From Stefan:

> It would be useful to know how best to implement the following: we have a single directory structure that contains all of the files needed to run a model. Each ensemble we run is a clone of this model. What would be the best way to minimise data transfers so that we only move the directory once, then clone in n replica times, then use each clone to run a replica? 

Hey Stefan, you can specify all the files to be staged in a list and use the ```shared_data``` attribute of the Resource Handle to stage these data once. You can copy or link these data between various locations on remote. There is no specfic example discussing shared data. Thanks for the ticket. I will add documentation for this one. Please see the [shared_data branch](https://github.com/radical-collaboration/GB-SC18/tree/shared_data) in this repo for my edit.

**Comment by sjzasada** [comment]
Thanks. I've tried running the modified version in the shared_data branch and it produces this error: 
BadParameter: invalid dir 

```
'/work/d137/d137/stef1/radical.pilot.sandbox/rp.session.parkin.lan.stef.017338.0007-pilot.0000/staging_area': mkdir: cannot create directory `/work/d137/d137': Permission denied
sh: cd: /work/d137/d137/stef1/radical.pilot.sandbox/rp.session.parkin.lan.stef.017338.0007-pilot.0000/staging_area: Not a directory
 (/Users/stef/Development/Radical/myenv/lib/python2.7/site-packages/saga/adaptors/shell/shell_file.py +352 (initialize)  :  raise saga.BadParameter ("invalid dir '%s': %s" % (self.url.path, out)))
Allocation failed: invalid dir '/work/d137/d137/stef1/radical.pilot.sandbox/rp.session.parkin.lan.stef.017338.0007-pilot.0000/staging_area': mkdir: cannot create directory `/work/d137/d137': Permission denied
sh: cd: /work/d137/d137/stef1/radical.pilot.sandbox/rp.session.parkin.lan.stef.017338.0007-pilot.0000/staging_area: Not a directory
```

It isn't clear from looking at the shell_files.py code why this happens. Is there something extra that I should have configured? I've searched the ensembletk documentation and can't really find much about shared data. 

Thanks.

**Comment by vivek-bala** [comment]
Hey Stefan, is this the error when running on archer? Is "d137" the project you use? This looks more like a permission error to create the 'staging_area' folder which will hold all the shared data.

On another note, I'm working on the documentation issues in entk. I should have most of them covered by end of tomorrow.

**Comment by sjzasada** [comment]
Yes, this happens on Archer when the version of the script you modified is run. Note, it is caused by the inclusion of the line:

```
cluster.shared_data = my_list
```

If this line is omitted and data is staged with 

```
k.upload_input_data = my_list
```

the relevant pilot sandbox directory is created (e.g. `/work/d137/d137/stef1/radical.pilot.sandbox/rp.session.parkin.lan.stef.017338.0007-pilot.0000`) is created. 

However, when the shared_data array is included an error is thrown creating, e.g. 
```
/work/d137/d137/stef1/radical.pilot.sandbox/rp.session.parkin.lan.stef.017338.0007-pilot.0000/staging_area
```
but it will still create 
```
/work/d137/d137/stef1/radical.pilot.sandbox/rp.session.parkin.lan.stef.017338.0007-pilot.0000
````

So I don't think there is a permission issue there as such (unless when creating the staging_area directory, Radical is using a different account?). 

I've poked around in the code a little, and line 320 in shell_file.py is trying to execute: 

```
mkdir -p / && cd / &&  mkdir -p '/work/d137/d137/stef1/radical.pilot.sandbox/rp.session.parkin.lan.stef.017338.0034-pilot.0000/staging_area';  cd '/work/d137/d137/stef1/radical.pilot.sandbox/rp.session.parkin.lan.stef.017338.0034-pilot.0000/staging_area'
```

If I execute this from a login shell on Archer it works fine.   It looks to me to be either a bug or a problem with the Archer configuration. Any idea what could be causing this?

**Comment by andre-merzky** [comment]
Is that directory available on the compute noxes, or only on the headnode?

**Comment by vivek-bala** [comment]
This seems to be coming from the RP layer. Not exactly sure why it can create the sandbox but not the staging_area. @andre-merzky any idea why this might be happening? I remember there were some [VE changes](https://github.com/radical-cybertools/radical.pilot/issues/1222) that had to be made on archer.

**Comment by sjzasada** [comment]
@andre-merzky Yes, everything under /work is available from the compute nodes.

**Comment by andre-merzky** [comment]
Hmm, I am out of ideas - I can't see why that command would not work when executed via RP, compared to being executed interactively.  We don't use different accounts (unless that is specified in the RP session or your .ssh/config).  The error appears in the client side logfiles, not in the agent logfiles in the pilot sandbox, correct?  

For more debug information, please run the application again with 
```
RADICAL_SAGA_PTY_VERBOSE=DEBUG
RADICAL_SAGA_PTY_LOG_TGT=log.out
RADICAL_VERBOSE=DEBUG
RADICAL_LOG_TGT=log.out
```
and send the resulting log files.  Thanks!

**Comment by sjzasada** [comment]
Here are the log files. 

The odd thing is that when it executes the command: 

`mkdir -p / && cd / &&  mkdir -p '/work/d137/d137/stef1/radical.pilot.sandbox/rp.session.parkin.lan.stef.017338.0039-pilot.0000/staging_area' ;  cd '/work/d137/d137/stef1/radical.pilot.sandbox/rp.session.parkin.lan.stef.017338.0039-pilot.0000/staging_area'`

It fails with 

`Allocation failed: invalid dir '/work/d137/d137/stef1/radical.pilot.sandbox/rp.session.parkin.lan.stef.017338.0039-pilot.0000/staging_area': mkdir: cannot create directory `/work/d137/d137': Permission denied`

But when the same script executes: 

`mkdir -p / && cd / &&  mkdir -p '/work/d137/d137/stef1/radical.pilot.sandbox/rp.session.parkin.lan.stef.017338.0039-pilot.0000/' ;  cd '/work/d137/d137/stef1/radical.pilot.sandbox/rp.session.parkin.lan.stef.017338.0039-pilot.0000/'`

The directory is created. 
[log.out.txt](https://github.com/radical-collaboration/GB-SC18/files/1092062/log.out.txt)

(I put in some extra logging to see what commands were being executed)

Thanks.

**Comment by andre-merzky** [comment]
Thanks Stephan!

Can you please run the following set of commands on `eslogin008`, please?

```
export PS1='$' ; set prompt='$'                                                  
export PS1='$' > /dev/null 2>&1 || set prompt='$'                                
printf 'HELLO_%d_SAGA\n' 1                                                       
stty -echo ; exec /bin/sh -i                                                     
unset PROMPT_COMMAND; set HISTFILE=$HOME/.saga_history; PS1='PROMPT-$?->'; PS2=''; export PS1 PS2 2>&1 >/dev/null; cd $HOME 2>&1 >/dev/null
mkdir -p / && cd / &&  mkdir -p '/work/d137/d137/stef1/radical.pilot.sandbox/rp.session.parkin.lan.stef.017338.0039-pilot.0000/staging_area' ;  cd '/work/d137/d137/stef1/radical.pilot.sandbox/rp.session.parkin.lan.stef.017338.0039-pilot.0000/staging_area'
```

Note the `stty -echo ; exec /bin/sh -i ` - that will create a new shell, and turn off echo, so the terminal will be somewhat unusable - you still get stdout/stderr from commands though.  

Thanks!

**Comment by andre-merzky** [comment]
Hi again, 

I managed to revive my archer account, and actually also have access to `d137`!  While I did not manage to run a pilot (no allocation left), I *could* stage data ok, and the `staging_area` got created without any troubles.

What I did is to run the RP code in `examples/07_shared_unit_data.py epsrc.archer`, after changing the project to `d137` in `examples/config.json`.  I am not sure what the equivalent test on entk level is - but, if you don't mind, could you give the RP layer a try, please?

**Comment by vivek-bala** [comment]
That would indeed be the correct equivalent. Hey Stefan, please give the example a try. You can use the same virtual environment as you have used for entk.

Let me try to simplify a bit. Once you have sourced your virtualenv, please run the following:
```
wget https://raw.githubusercontent.com/radical-cybertools/radical.pilot/master/examples/07_shared_unit_data.py
wget https://github.com/radical-cybertools/radical.pilot/blob/master/examples/config.json

# edit config.json to add the correct project id

python 07_shared_unit_data.py epsrc.json
```

**Comment by vivek-bala** [comment]
Note that (unlike the entk script) you cannot set the username in this rp script directly. The quickest (probably recommended) method would be to set your ssh config file in $HOME appropriately. If you already have setup the ssh config file, please ignore.

Your .ssh/config file should look like the following:
```
Host login.archer.ac.uk
    Hostname login.archer.ac.uk
    User <archer username>
```

**Comment by sjzasada** [comment]
Hi Andre,

I can confirm that these commands do create the folder:

stef1@eslogin001:~> export PS1='$' ; set prompt='$'
$export PS1='$' > /dev/null 2>&1 || set prompt='$'
$printf 'HELLO_%d_SAGA\n' 1
HELLO_1_SAGA
$stty -echo ; exec /bin/sh -i
eslogin001:~> PROMPT-0->PROMPT-0->/work/d137/d137/stef1/radical.pilot.sandbox/rp.session.parkin.lan.stef.017338.0039-pilot.0000/staging_area
PROMPT-0->


Stefan



On 21 Jun 2017, at 21:07, Andre Merzky <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks Stephan!

Can you please run the following set of commands on eslogin008, please?

export PS1='$' ; set prompt='$'
export PS1='$' > /dev/null 2>&1 || set prompt='$'
printf 'HELLO_%d_SAGA\n' 1
stty -echo ; exec /bin/sh -i
unset PROMPT_COMMAND; set HISTFILE=$HOME/.saga_history; PS1='PROMPT-$?->'; PS2=''; export PS1 PS2 2>&1 >/dev/null; cd $HOME 2>&1 >/dev/null
mkdir -p / && cd / &&  mkdir -p '/work/d137/d137/stef1/radical.pilot.sandbox/rp.session.parkin.lan.stef.017338.0039-pilot.0000/staging_area' ;  cd '/work/d137/d137/stef1/radical.pilot.sandbox/rp.session.parkin.lan.stef.017338.0039-pilot.0000/staging_area'


Note the stty -echo ; exec /bin/sh -i - that will create a new shell, and turn off echo, so the terminal will be somewhat unusable - you still get stdout/stderr from commands though.

Thanks!

**Comment by sjzasada** [comment]
Hi @vivek-bala 

I’ve come up against another problem here (which I’ve experienced before). My .ssh/config file is set up correctly: 

```
Host archer
                HostName login.archer.ac.uk
                User stef1
```

This works fine if I `ssh archer` from the command line. However, Radical logs in with the username from my laptop (stef). 

The `python 07_shared_unit_data.py epsrc.archer` command therefore fails. 

Note, I have two accounts on archer (stef & stef1) so logging in using my local username (stef) does work. However, the stef account is linked to a project that has now ended. 

Could this be the root of the other problem I was having? And do you have any idea why radical is not reading the username from my .ssh/config file? 

Thanks, 

Stefan

**Comment by sjzasada** [comment]
Further to this, I've just tried removing the authorized_key for my stef account so that ssh stef@login.archer.ac.uk doesn't happen automatically. 

The radical pilot job now fails with 

`Password: ) (/Users/stef/Development/Radical/myenv/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py +315 (_initialize_pty)  :  % match))`

hence it is still not readying me .ssh/config settings.

**Comment by vivek-bala** [comment]
Can you edit the ssh config file as follows:

```
Host archer epsrc.archer login.archer.ac.uk
    Hostname login.archer.ac.uk
    User stef1
```

and try again please? I have another method that will definitely work but requires adding some more code to the script (and possible deprecated/ not recommended).

**Comment by sjzasada** [comment]
Thanks Vivek,

On 22 Jun 2017, at 16:13, Vivekanandan (Vivek) Balasubramanian <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you edit the ssh config file as follows:

Host archer epsrc.archer login.archer.ac.uk<http://login.archer.ac.uk/>
    Hostname login.archer.ac.uk<http://login.archer.ac.uk/>
    User stef1


and try again please? I have another method that will definitely work but requires adding some more code to the script (and possible deprecated/ not recommended).

This works now. I will try it with the shared staging next.

Cheers,

Stefan

**Comment by vivek-bala** [comment]
Great! Keep me posted!
